spring:
  profiles:
    active: local
  application:
    name: GlanceChatBackend
  mongodb:
    username: ${MONGO_USERNAME:root}
    password: ${MONGO_PASSWORD:1234}
    host: ${MONGO_HOST:localhost}
    port: ${MONGO_PORT:27017}
    database: ${MONGO_DATABASE:glance_chat}
    authentication-database: admin
  mvc:
    problemdetails:
      enabled: true

error:
  url: ${ERROR_URL:http://localhost:8080/error}

jwt:
  secret: ${JWT_SECRET:your_jwt_secret_key}
  expiration: ${JWT_EXPIRATION:3600000} # 1 hour in milliseconds
  issuer: ${JWT_ISSUER:glance_chat_backend}

mail:
  host: ${MAIL_HOST:smtp.example.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:username}
  password: ${MAIL_PASSWORD:password}

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY:admin}
    secret-key: ${AWS_SECRET_KEY:123456789}
    bucket-name: ${AWS_S3_BUCKET_NAME:avatars}
    region: ${AWS_REGION:us-east-1}
    url: ${AWS_S3_URL:http://localhost:9000}
    public-url: ${AWS_S3_PUBLIC_URL:http://localhost:9000/avatars}  # host/bucket

